# Generated by Django 2.2 on 2019-04-15 11:59

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_pasien', models.BooleanField(default=False)),
                ('is_dokter', models.BooleanField(default=False)),
                ('is_manajer', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('no_hp', models.CharField(max_length=255, null=True)),
                ('jenisKelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('alamat', models.CharField(max_length=255, null=True)),
                ('tanggalLahir', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='charts/%Y/%m/%d')),
                ('tipe', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nama', models.CharField(max_length=255)),
                ('ktp', models.CharField(max_length=255)),
                ('strDokter', models.CharField(max_length=255)),
                ('jenisKelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('alamat', models.CharField(max_length=255)),
                ('tanggalLahir', models.DateField()),
                ('no_hp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manajer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nama', models.CharField(max_length=255)),
                ('ktp', models.CharField(max_length=255)),
                ('no_hp', models.CharField(max_length=255)),
                ('jenisKelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('alamat', models.CharField(max_length=255)),
                ('tanggalLahir', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RekamMedis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anamnesa', models.CharField(max_length=255)),
                ('alergi', models.CharField(max_length=255, null=True)),
                ('riwayat_penyakit', models.CharField(max_length=255, null=True)),
                ('tekanan_darah', models.FloatField(null=True)),
                ('berat', models.FloatField(null=True)),
                ('tinggi', models.FloatField(null=True)),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Pasien')),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Dokter')),
            ],
        ),
        migrations.AddField(
            model_name='pasien',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OHIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kondisi', models.CharField(max_length=255)),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.RekamMedis')),
            ],
        ),
        migrations.CreateModel(
            name='Gigi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=2)),
                ('d', models.IntegerField()),
                ('l', models.IntegerField()),
                ('o', models.IntegerField(null=True)),
                ('m', models.IntegerField()),
                ('v', models.IntegerField()),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.RekamMedis')),
            ],
        ),
        migrations.CreateModel(
            name='FotoRontgen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.RekamMedis')),
            ],
        ),
    ]
