# Generated by Django 2.1.6 on 2019-04-05 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekamMedis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anamnesa', models.CharField(max_length=255)),
                ('alergi', models.CharField(max_length=255, null=True)),
                ('riwayat_penyakit', models.CharField(max_length=255, null=True)),
                ('tekanan_darah', models.FloatField(null=True)),
                ('berat', models.FloatField(null=True)),
                ('tinggi', models.FloatField(null=True)),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Dokter')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Pasien')),
            ],
        ),
    ]
