# Generated by Django 2.2 on 2019-04-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
                ('emailInstansi', models.CharField(max_length=255)),
                ('no_telepon', models.CharField(max_length=255)),
                ('layanan', models.CharField(max_length=255)),
                ('waktuLayanan', models.CharField(max_length=255)),
            ],
        ),
    ]
