# Generated by Django 2.1.6 on 2019-04-05 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rekammedis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gigi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=2)),
                ('kondisi', models.IntegerField()),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.RekamMedis')),
            ],
        ),
    ]
