# Generated by Django 2.2 on 2019-04-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20190421_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigi',
            name='ci',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gigi',
            name='di',
            field=models.IntegerField(null=True),
        ),
    ]
