# Generated by Django 2.1.6 on 2019-04-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_gigi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gigi',
            old_name='kondisi',
            new_name='d',
        ),
        migrations.AddField(
            model_name='gigi',
            name='l',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gigi',
            name='m',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gigi',
            name='o',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gigi',
            name='v',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
