# Generated by Django 2.2 on 2019-05-05 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20190429_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_booked', models.BooleanField(default=False)),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Dokter')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalPraktek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_mulai', models.DateTimeField()),
                ('waktu_selesai', models.DateTimeField()),
                ('no_ruangan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JenisPenanganan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Penanganan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Appointment')),
                ('jenis_penanganan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.JenisPenanganan')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='jadwal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.JadwalPraktek'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pasien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Pasien'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rekam_medis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.RekamMedis'),
        ),
    ]
