# Generated by Django 2.1.6 on 2019-04-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20190406_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigi',
            name='o',
            field=models.IntegerField(null=True),
        ),
    ]
