# Generated by Django 2.1.6 on 2019-04-06 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20190406_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kondisi', models.CharField(max_length=2)),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.RekamMedis')),
            ],
        ),
    ]
