# Generated by Django 2.2 on 2019-05-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20190506_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='JawabanSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('jawaban', models.CharField(max_length=255)),
                ('dokter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Dokter')),
            ],
        ),
    ]
