# Generated by Django 2.2 on 2019-05-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_jawabansurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabansurvey',
            name='tipe',
            field=models.CharField(default='tf', max_length=255),
            preserve_default=False,
        ),
    ]
