# Generated by Django 2.2 on 2019-05-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_jawabansurvey_tipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawabansurvey',
            name='jawaban',
            field=models.IntegerField(),
        ),
    ]
