# Generated by Django 2.2 on 2019-05-10 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20190508_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='rekam_medis',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.RekamMedis'),
        ),
    ]
