# Generated by Django 2.2 on 2019-05-10 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20190510_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penanganan',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='penanganan',
            name='jenis_penanganan',
        ),
        migrations.AddField(
            model_name='penanganan',
            name='art',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='penanganan',
            name='cpp_acp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='penanganan',
            name='dhe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='penanganan',
            name='eks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='penanganan',
            name='fs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='penanganan',
            name='lainnya',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='penanganan',
            name='sp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='penanganan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Penanganan'),
        ),
        migrations.DeleteModel(
            name='JenisPenanganan',
        ),
    ]
