# Generated by Django 2.2.1 on 2019-05-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_auto_20190510_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotorontgen',
            name='foto',
            field=models.ImageField(upload_to='rontgents'),
        ),
    ]
