# Generated by Django 2.2.1 on 2019-05-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_auto_20190513_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekammedis',
            name='tekanan_darah',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
